import test, { almost, is, ok, rejects, throws } from 'tst'
import { createServer } from 'node:http'
import { createHash } from 'node:crypto'
import { readFileSync, existsSync, mkdtempSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import { load, tensor, backends, fetchModel } from './runtime.js'

// Fixtures — generated by fixtures/make.py (pip3 install onnx; no torch needed).
const LINEAR = readFileSync(new URL('./fixtures/linear-relu.onnx', import.meta.url))
const LINEAR_URL = new URL('./fixtures/linear-relu.onnx', import.meta.url)
const SCALE = readFileSync(new URL('./fixtures/scale-shift.onnx', import.meta.url))

// Isolate the Node disk cache from the user's real ~/.cache for the whole run.
const CACHE_DIR = mkdtempSync(path.join(os.tmpdir(), 'audiojs-neural-runtime-cache-'))
process.env.AUDIO_NEURAL_CACHE = CACHE_DIR

function cacheKey(url) {
  return path.join(CACHE_DIR, createHash('sha256').update(url).digest('hex'))
}

// y = relu(x @ W + b), W = [[1,0,-1],[0.5,-0.5,2]], b = [0.1,0,-0.2] (fixtures/make.py).
// x = [1,2] → row@W = [2.1,-1,3], +b = [2.1,-1,2.8], relu = [2.1,0,2.8].
const EXPECTED = [2.1, 0, 2.8]

test('load(bytes) — run() matches the hand-computed relu(x@W+b)', async () => {
  let session = await load(LINEAR)
  let out = await session.run({ x: tensor(Float32Array.from([1, 2]), [1, 2]) })
  is(out.y.dims, [1, 3])
  is(out.y.type, 'float32')
  for (let i = 0; i < 3; i++) almost(out.y.data[i], EXPECTED[i], 1e-6, `y[${i}]`)
  session.free()
})

test('load — file:// URL loads and runs', async () => {
  let session = await load(LINEAR_URL.href)
  let out = await session.run({ x: tensor(Float32Array.from([1, 2]), [1, 2]) })
  for (let i = 0; i < 3; i++) almost(out.y.data[i], EXPECTED[i], 1e-6, `y[${i}]`)
  session.free()
})

test('load — http URL: fetched, cached to disk, progress reports loaded/total', async () => {
  let requests = 0
  let server = createServer((req, res) => {
    requests++
    res.setHeader('Content-Length', String(LINEAR.length))
    res.end(LINEAR)
  })
  await new Promise(resolve => server.listen(0, resolve))
  let url = `http://localhost:${server.address().port}/model.onnx`

  let calls = []
  let bytes = await fetchModel(url, { progress: p => calls.push(p) })
  is(bytes.length, LINEAR.length, 'downloaded byte count')
  ok(calls.length > 0, 'progress called at least once')
  let last = calls.at(-1)
  is(last.loaded, LINEAR.length, 'final loaded == full size')
  is(last.total, LINEAR.length, 'total from Content-Length')

  let file = cacheKey(url)
  ok(existsSync(file), 'cache file written under $AUDIO_NEURAL_CACHE')
  is(readFileSync(file).length, LINEAR.length, 'cache file byte-for-byte')

  let bytes2 = await fetchModel(url) // second load — cache hit
  is(bytes2.length, LINEAR.length)
  is(requests, 1, 'server saw exactly one request')

  await new Promise(resolve => server.close(resolve))
})

test('fetchModel — corrupted cache entry re-fetches', async () => {
  let requests = 0
  let server = createServer((req, res) => {
    requests++
    res.setHeader('Content-Length', String(LINEAR.length))
    res.end(LINEAR)
  })
  await new Promise(resolve => server.listen(0, resolve))
  let url = `http://localhost:${server.address().port}/corrupt.onnx`

  await fetchModel(url) // populate cache
  is(requests, 1)
  let file = cacheKey(url)
  let truncated = readFileSync(file).subarray(0, -1) // delete a byte
  writeFileSync(file, truncated)

  let bytes = await fetchModel(url)
  is(bytes.length, LINEAR.length, 're-downloaded full model')
  is(requests, 2, 'corrupted cache entry forced a second request')

  await new Promise(resolve => server.close(resolve))
})

test('load — dynamic batch dim: batch 1 and batch 4 both run; input metadata name', async () => {
  let session = await load(SCALE)
  is(session.inputs.length, 1)
  is(session.inputs[0].name, 'x')
  is(session.outputs[0].name, 'y')

  let o1 = await session.run({ x: tensor(Float32Array.from([5]), [1]) })
  almost(o1.y.data[0], 11, 1e-6) // 5*2+1

  let o4 = await session.run({ x: tensor(Float32Array.from([1, 2, 3, 4]), [4]) })
  let expect4 = [1, 2, 3, 4].map(v => v * 2 + 1)
  for (let i = 0; i < 4; i++) almost(o4.y.data[i], expect4[i], 1e-6, `batch4[${i}]`)

  session.free()
})

test('load — bad model bytes rejects with a clear message', async () => {
  await rejects(() => load(new Uint8Array([1, 2, 3, 4, 5])), /neural-runtime: failed to load model/)
})

test("load — backend 'webgpu' in Node rejects naming the requirement", async () => {
  await rejects(() => load(LINEAR, { backend: 'webgpu' }), /onnxruntime-web/)
})

test('free — idempotent; run() after free() throws', async () => {
  let session = await load(LINEAR)
  session.free()
  session.free() // idempotent — must not throw
  await rejects(() => session.run({ x: tensor(Float32Array.from([1, 2]), [1, 2]) }), /free/)
})

test('run — 8 concurrent calls resolve independently and correctly', async () => {
  let session = await load(SCALE)
  let values = [1, 2, 3, 4, 5, 6, 7, 8]
  let results = await Promise.all(values.map(v => session.run({ x: tensor(Float32Array.from([v]), [1]) })))
  results.forEach((r, i) => almost(r.y.data[0], values[i] * 2 + 1, 1e-6, `run ${i}`))
  session.free()
})

test('tensor — infers type from data constructor, throws when ambiguous', () => {
  is(tensor(Float32Array.from([1]), [1]).type, 'float32')
  is(tensor(Int32Array.from([1]), [1]).type, 'int32')
  is(tensor(BigInt64Array.from([1n]), [1]).type, 'int64')
  is(tensor(new Uint8Array([1]), [1]).type, 'uint8')
  is(tensor(['a', 'b'], [2]).type, 'string')
  throws(() => tensor([1, 2], [2]), undefined, 'plain number[] is ambiguous (int32? float32?)')
  throws(() => tensor(Float32Array.from([1]), undefined), undefined, 'dims required')
})

test('backends — Node reports only \'node\'', async () => {
  is(await backends(), ['node'])
})
