// Fixture: fixtures/identity-mask.onnx, generated by fixtures/make.py
// (python3 -m venv .venv && .venv/bin/pip install onnx && .venv/bin/python3 fixtures/make.py)
import test, { ok, is, rejects } from 'tst'
import { existsSync, readFileSync } from 'node:fs'
import separate, { stft, istft, wienerFilter } from './separate.js'

// ---------------------------------------------------------------- utilities

function seededRand(seed) {
	let s = seed >>> 0
	return () => { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296 }
}

// Simplified SDR (Vincent, Gribonval, Févotte, "Performance measurement in
// blind audio source separation", IEEE TASLP 2006): 10·log10(Σref² / Σ(est−ref)²).
// No permutation/filter search (targets are already aligned by construction
// in every test here) — a direct energy-ratio proxy, adequate for synthetic
// oracle signals with known ground truth.
function sdr(est, ref) {
	let n = Math.min(est.length, ref.length)
	let num = 0, den = 0
	for (let i = 0; i < n; i++) { num += ref[i] * ref[i]; let d = est[i] - ref[i]; den += d * d }
	return 10 * Math.log10(num / (den + 1e-300))
}

function snrRange(a, b, from, to) {
	let sig = 0, err = 0
	for (let i = from; i < to; i++) { sig += b[i] * b[i]; let d = a[i] - b[i]; err += d * d }
	return 10 * Math.log10(sig / (err + 1e-300))
}

function magOf(chStft) {
	let T = chStft.re.length, bins = chStft.bins
	let out = new Array(T)
	for (let t = 0; t < T; t++) {
		let re = chStft.re[t], im = chStft.im[t]
		let a = new Float64Array(bins)
		for (let f = 0; f < bins; f++) a[f] = Math.sqrt(re[f] * re[f] + im[f] * im[f])
		out[t] = a
	}
	return out
}

// Mock ONNX session matching @audio/neural-runtime's Session interface —
// enough for separate() to drive it (inputs/outputs metadata, run(feeds)).
function mockSession(run, ioNames = { in: 'input', out: 'output' }) {
	return {
		inputs: [{ name: ioNames.in }],
		outputs: [{ name: ioNames.out }],
		async run(feeds) { return { [ioNames.out]: await run(feeds[ioNames.in]) } },
		free() {},
	}
}

// Oracle "mask" mock for modelType 'mask': mask = 1 inside [lo, hi] Hz, 0
// outside. For spectrally-disjoint sources this reproduces the true
// per-target magnitude exactly (the other source contributes ~0 in-band).
function bandMaskSession(lo, hi, n, rate) {
	return mockSession(async input => {
		let [, C, F, T] = input.dims
		let data = new Float32Array(C * F * T)
		let binHz = rate / n
		for (let f = 0; f < F; f++) {
			let m = (f * binHz >= lo && f * binHz <= hi) ? 1 : 0
			for (let c = 0; c < C; c++) for (let t = 0; t < T; t++) data[c * F * T + f * T + t] = m
		}
		return { data, dims: input.dims, type: 'float32' }
	}, { in: 'mag', out: 'mask' })
}

function sine(freqs, amp, fs, N, vibratoHz = 0, vibratoDepth = 0) {
	let x = new Float32Array(N)
	for (let i = 0; i < N; i++) {
		let t = i / fs
		let vib = vibratoHz ? 1 + vibratoDepth * Math.sin(2 * Math.PI * vibratoHz * t) : 1
		let s = 0
		for (let f of freqs) s += Math.sin(2 * Math.PI * f * vib * t)
		x[i] = amp * s / freqs.length
	}
	return x
}

// ---------------------------------------------------------- 1. STFT/iSTFT

test('stft/istft — identity round trip, SNR > 120 dB (random stereo, 3 s)', () => {
	let fs = 44100, N = Math.round(fs * 3)
	let rand = seededRand(42)
	for (let ch = 0; ch < 2; ch++) {
		let x = new Float32Array(N)
		for (let i = 0; i < N; i++) x[i] = (rand() * 2 - 1) * 0.5
		let frames = stft(x, { n: 4096, hop: 1024 })
		let y = istft(frames, { length: N })
		is(y.length, N)
		let db = sdr(y, x)
		ok(db > 120, `channel ${ch}: SNR ${db.toFixed(1)} dB`)
	}
})

test('stft — frame count matches torch.stft(center=True) formula: 1 + floor(N/hop)', () => {
	let fs = 44100
	for (let durMs of [50, 700, 1000, 3333, 30000]) {
		let N = Math.round(fs * durMs / 1000)
		let x = new Float32Array(N)
		let frames = stft(x, { n: 4096, hop: 1024 })
		is(frames.re.length, 1 + Math.floor(N / 1024), `N=${N}`)
	}
})

// ------------------------------------------------------- 2. Oracle separation

// Mock session returning the *true* magnitude of a known (stereo) target —
// its own STFT per channel, computed independently of the mixture — matching
// modelType 'openunmix' semantics (magnitude estimate, not a mask). Correct
// only for a single chunk (one run() call covering the whole signal), which
// every use below satisfies (signal length < the 30 s default chunk).
function trueMagnitudeSession(targetChannels, n, hop, perturb) {
	let mags = targetChannels.map(ch => magOf(stft(ch, { n, hop })))
	return mockSession(async input => {
		let [, C, F, T] = input.dims
		let data = new Float32Array(C * F * T)
		for (let c = 0; c < C; c++) for (let t = 0; t < T; t++) for (let f = 0; f < F; f++) {
			let v = mags[c][t][f]
			data[c * F * T + f * T + t] = perturb ? perturb(v) : v
		}
		return { data, dims: input.dims, type: 'float32' }
	}, { in: 'mag', out: 'mag' })
}

// Genuinely stereo bass/vocal (distinct L/R gain and vibrato rate) — a
// mono-duplicated (L≡R) mixture gives a rank-1 spatial covariance matrix per
// bin, a degenerate case for multichannel Wiener EM (see README limitations);
// real stereo content doesn't hit it, so the oracle tests use real content.
function stereoSources(fs, N) {
	let bassL = sine([60, 90, 120, 150, 180], 0.5, fs, N) // 60–200 Hz harmonic
	let bassR = sine([60, 90, 120, 150, 180], 0.45, fs, N)
	let vocalL = sine([300, 500, 800, 1200, 1800, 2500], 0.4, fs, N, 5, 0.003) // 300–3000 Hz formant-like + vibrato
	let vocalR = sine([300, 500, 800, 1200, 1800, 2500], 0.4, fs, N, 5.2, 0.0025)
	let mixL = new Float32Array(N), mixR = new Float32Array(N)
	for (let i = 0; i < N; i++) { mixL[i] = bassL[i] + vocalL[i]; mixR[i] = bassR[i] + vocalR[i] }
	return { bass: [bassL, bassR], vocal: [vocalL, vocalR], mix: [mixL, mixR] }
}

test('separate — oracle (true stem magnitude), disjoint bass/vocal bands: SDR > 15 dB (wiener:0); wiener:1 does not regress (≥ −0.1 dB)', async () => {
	let fs = 44100, N = Math.round(fs * 4)
	let { bass, vocal, mix } = stereoSources(fs, N)

	let model = { bass: 'b', vocal: 'v' }
	let sessionFactory = async spec => spec === 'b' ? trueMagnitudeSession(bass, 4096, 1024) : trueMagnitudeSession(vocal, 4096, 1024)

	let r0 = await separate(mix, { sampleRate: fs, modelType: 'openunmix', model, session: sessionFactory, wiener: 0 })
	let r1 = await separate(mix, { sampleRate: fs, modelType: 'openunmix', model, session: sessionFactory, wiener: 1 })

	let bassSdr0 = sdr(r0.stems.bass[0], bass[0]), vocalSdr0 = sdr(r0.stems.vocal[0], vocal[0])
	let bassSdr1 = sdr(r1.stems.bass[0], bass[0]), vocalSdr1 = sdr(r1.stems.vocal[0], vocal[0])
	ok(bassSdr0 > 15, `wiener:0 bass SDR ${bassSdr0.toFixed(1)} dB`)
	ok(vocalSdr0 > 15, `wiener:0 vocal SDR ${vocalSdr0.toFixed(1)} dB`)
	ok(bassSdr1 >= bassSdr0 - 0.1, `wiener:1 bass SDR ${bassSdr1.toFixed(1)} vs wiener:0 ${bassSdr0.toFixed(1)}`)
	ok(vocalSdr1 >= vocalSdr0 - 0.1, `wiener:1 vocal SDR ${vocalSdr1.toFixed(1)} vs wiener:0 ${vocalSdr0.toFixed(1)}`)
})

test('separate — noisy magnitude estimates (×(1+0.3·noise)): wiener:1 beats wiener:0 by ≥ 1 dB', async () => {
	let fs = 44100, N = Math.round(fs * 4)
	let { bass, vocal, mix } = stereoSources(fs, N)

	let rand = seededRand(99)
	let perturb = v => Math.max(0, v * (1 + 0.3 * (rand() * 2 - 1)))
	let model = { bass: 'b', vocal: 'v' }
	let sessionFactory = async spec => spec === 'b' ? trueMagnitudeSession(bass, 4096, 1024, perturb) : trueMagnitudeSession(vocal, 4096, 1024, perturb)

	let r0 = await separate(mix, { sampleRate: fs, modelType: 'openunmix', model, session: sessionFactory, wiener: 0 })
	let r1 = await separate(mix, { sampleRate: fs, modelType: 'openunmix', model, session: sessionFactory, wiener: 1 })

	let bassSdr0 = sdr(r0.stems.bass[0], bass[0]), vocalSdr0 = sdr(r0.stems.vocal[0], vocal[0])
	let bassSdr1 = sdr(r1.stems.bass[0], bass[0]), vocalSdr1 = sdr(r1.stems.vocal[0], vocal[0])
	ok(bassSdr1 >= bassSdr0 + 1, `wiener:1 ${bassSdr1.toFixed(1)} vs wiener:0 ${bassSdr0.toFixed(1)} dB (bass)`)
	ok(vocalSdr1 >= vocalSdr0 + 1, `wiener:1 ${vocalSdr1.toFixed(1)} vs wiener:0 ${vocalSdr0.toFixed(1)} dB (vocal)`)
})

// --------------------------------------------------------- 3. wienerFilter unit

test('wienerFilter — softmask ratio mask sums exactly to the mixture (iterations:0)', () => {
	let fs = 44100, N = Math.round(fs * 1)
	let bass = sine([80, 160], 0.3, fs, N), vocal = sine([500, 1200], 0.15, fs, N)
	let mix = new Float32Array(N)
	for (let i = 0; i < N; i++) mix[i] = bass[i] + vocal[i]

	let mixStft = [stft(mix, { n: 4096, hop: 1024 })]
	let estimates = { bass: [magOf(stft(bass, { n: 4096, hop: 1024 }))], vocal: [magOf(stft(vocal, { n: 4096, hop: 1024 }))] }
	let out = wienerFilter(mixStft, estimates, { iterations: 0, softmask: true })

	let T = mixStft[0].re.length, bins = mixStft[0].bins
	let maxErr = 0
	for (let t = 0; t < T; t++) for (let f = 0; f < bins; f++) {
		let sre = out.bass[0].re[t][f] + out.vocal[0].re[t][f]
		let sim = out.bass[0].im[t][f] + out.vocal[0].im[t][f]
		maxErr = Math.max(maxErr, Math.abs(sre - mixStft[0].re[t][f]), Math.abs(sim - mixStft[0].im[t][f]))
	}
	ok(maxErr < 1e-4, `max |Σ stems − mix| = ${maxErr}`)
})

test('wienerFilter — residual:true makes the sum exact (iterations:0, any softmask)', () => {
	let fs = 44100, N = Math.round(fs * 1)
	let bass = sine([80, 160], 0.3, fs, N), vocal = sine([500, 1200], 0.15, fs, N)
	let mix = new Float32Array(N)
	for (let i = 0; i < N; i++) mix[i] = bass[i] + vocal[i]

	let mixStft = [stft(mix, { n: 4096, hop: 1024 })]
	// deliberately imperfect estimates (perturbed) — residual must still absorb the gap exactly
	let rand = seededRand(3)
	let estimates = {
		bass: [magOf(stft(bass, { n: 4096, hop: 1024 })).map(row => row.map(v => v * (1 + 0.5 * rand())))],
		vocal: [magOf(stft(vocal, { n: 4096, hop: 1024 })).map(row => row.map(v => v * (1 + 0.5 * rand())))],
	}
	let out = wienerFilter(mixStft, estimates, { iterations: 0, residual: true })
	ok('residual' in out, 'residual target present')

	let T = mixStft[0].re.length, bins = mixStft[0].bins
	let maxErr = 0
	for (let t = 0; t < T; t++) for (let f = 0; f < bins; f++) {
		let sre = out.bass[0].re[t][f] + out.vocal[0].re[t][f] + out.residual[0].re[t][f]
		let sim = out.bass[0].im[t][f] + out.vocal[0].im[t][f] + out.residual[0].im[t][f]
		maxErr = Math.max(maxErr, Math.abs(sre - mixStft[0].re[t][f]), Math.abs(sim - mixStft[0].im[t][f]))
	}
	ok(maxErr < 1e-9, `max |Σ stems + residual − mix| = ${maxErr}`)
})

test('wienerFilter — eps stability: all-silent input and estimates produce finite output (no NaN/Inf)', () => {
	let N = 8192
	let silence = new Float32Array(N)
	let mixStft = [stft(silence, { n: 4096, hop: 1024 })]
	let zeroMag = magOf(mixStft[0])
	for (let iterations of [0, 1, 2]) {
		let out = wienerFilter(mixStft, { a: [zeroMag], b: [zeroMag] }, { iterations })
		let T = mixStft[0].re.length, bins = mixStft[0].bins
		let finite = true
		for (let name of ['a', 'b']) for (let t = 0; t < T; t++) for (let f = 0; f < bins; f++) {
			if (!Number.isFinite(out[name][0].re[t][f]) || !Number.isFinite(out[name][0].im[t][f])) finite = false
		}
		ok(finite, `iterations=${iterations}: all finite`)
	}
})

// ------------------------------------------------------------------ 4. Chunking

test('separate — chunked (30s/2s overlap) matches single-chunk (1000s) within 60 dB in overlap regions', async () => {
	let fs = 44100, N = Math.round(fs * 70)
	let bass = sine([60, 90, 120, 150, 180], 0.5, fs, N)
	let vocal = sine([300, 500, 800, 1200, 1800, 2500], 0.4, fs, N)
	let mix = new Float32Array(N)
	for (let i = 0; i < N; i++) mix[i] = bass[i] + vocal[i]

	let model = { bass: 'b', vocal: 'v' }
	let sessionFactory = async spec => spec === 'b' ? bandMaskSession(0, 250, 4096, fs) : bandMaskSession(250, fs / 2, 4096, fs)
	let opts = { sampleRate: fs, modelType: 'mask', model, session: sessionFactory, wiener: 1 }

	let chunkLen = Math.round(30 * fs), overlapLen = Math.round(2 * fs), stepLen = chunkLen - overlapLen
	let starts = []
	for (let s = 0; s < N; s += stepLen) { starts.push(s); if (s + chunkLen >= N) break }
	ok(starts.length >= 2, `sanity: ${starts.length} chunks expected for 70s/30s/2s`)

	let r1 = await separate([mix, mix], { ...opts, chunk: 30, overlap: 2 })
	let r2 = await separate([mix, mix], { ...opts, chunk: 1000, overlap: 2 })

	for (let name of ['bass', 'vocal']) {
		let a = r1.stems[name][0], b = r2.stems[name][0]
		for (let i = 1; i < starts.length; i++) {
			let lo = starts[i], hi = Math.min(N, starts[i] + overlapLen)
			let db = snrRange(a, b, lo, hi)
			ok(db > 60, `${name} overlap region ${i}: ${db.toFixed(1)} dB`)
		}
	}
})

// -------------------------------------------------------------- 5. Waveform model

test('separate — waveform modelType (Demucs-class): mock returns true stems, SDR > 40 dB', async () => {
	let fs = 44100, N = Math.round(fs * 3)
	let bass = sine([90], 0.4, fs, N), vocal = sine([600], 0.3, fs, N)
	let mix = new Float32Array(N)
	for (let i = 0; i < N; i++) mix[i] = bass[i] + vocal[i]

	let trueStems = { bass: [bass, bass], vocal: [vocal, vocal] }
	let session = mockSession(async input => {
		let [, C, len] = input.dims, targets = ['bass', 'vocal'], S = targets.length
		let data = new Float32Array(S * C * len)
		for (let s = 0; s < S; s++) for (let c = 0; c < C; c++) data.set(trueStems[targets[s]][c].subarray(0, len), (s * C + c) * len)
		return { data, dims: [1, S, C, len], type: 'float32' }
	}, { in: 'mix', out: 'stems' })

	let result = await separate([mix, mix], {
		sampleRate: fs, modelType: 'waveform',
		model: { url: 'fake', targets: ['bass', 'vocal'] },
		session: async () => session,
	})

	let bassSdr = sdr(result.stems.bass[0], bass), vocalSdr = sdr(result.stems.vocal[0], vocal)
	ok(bassSdr > 40, `bass SDR ${bassSdr.toFixed(1)} dB`)
	ok(vocalSdr > 40, `vocal SDR ${vocalSdr.toFixed(1)} dB`)
})

// ------------------------------------------- 6. Mono duplication + resampling

test('separate — mono input duplicates to stereo output', async () => {
	let fs = 44100, N = Math.round(fs * 1)
	let mono = sine([440], 0.3, fs, N)
	let session = mockSession(async input => ({ data: Float32Array.from(input.data), dims: input.dims, type: 'float32' }))
	let result = await separate([mono], { sampleRate: fs, model: 'x', modelType: 'openunmix', wiener: 0, session: async () => session })
	is(result.stems.stem.length, 2, 'stereo output')
	is(result.stems.stem[0].length, N)
})

test('separate — targetRate resampling round trip (48k in, 44.1k model): output stays at input rate, duration ±1 ms', async () => {
	let fs = 48000, N = Math.round(fs * 2)
	let x = sine([440], 0.3, fs, N)
	let session = mockSession(async input => ({ data: Float32Array.from(input.data), dims: input.dims, type: 'float32' }))
	let result = await separate([x, x], {
		sampleRate: fs, targetRate: 44100, model: 'x', modelType: 'openunmix', wiener: 0,
		session: async () => session,
	})
	is(result.sampleRate, fs, 'output reported at input rate')
	let durDiffMs = Math.abs(result.stems.stem[0].length - N) / fs * 1000
	ok(durDiffMs <= 1, `duration diff ${durDiffMs.toFixed(3)} ms`)
	let db = sdr(result.stems.stem[0], x)
	ok(db > 30, `round-trip SDR ${db.toFixed(1)} dB`)
})

// ------------------------------------------------- 7. Real ONNX (no weights)

const IDENTITY_ONNX_PATH = new URL('./fixtures/identity-mask.onnx', import.meta.url)
const hasIdentityFixture = existsSync(IDENTITY_ONNX_PATH)

;(hasIdentityFixture ? test : test.skip)('separate — real @audio/neural-runtime session (identity-mask.onnx): returns mixture as the single stem, SDR > 60 dB', async () => {
	// wiener:0 isolates the runtime/tensor-marshalling path being proven here from
	// Wiener-EM's own (separately tested) behavior — see test 3/oracle tests above.
	let fs = 44100, N = Math.round(fs * 1)
	let rand = seededRand(11)
	let L = new Float32Array(N), R = new Float32Array(N)
	for (let i = 0; i < N; i++) { L[i] = 0.3 * Math.sin(2 * Math.PI * 220 * i / fs) + 0.05 * (rand() * 2 - 1); R[i] = 0.3 * Math.sin(2 * Math.PI * 330 * i / fs) + 0.05 * (rand() * 2 - 1) }

	let bytes = readFileSync(IDENTITY_ONNX_PATH)
	let result = await separate([L, R], { sampleRate: fs, model: bytes, modelType: 'openunmix', wiener: 0 })

	is(Object.keys(result.stems).length, 1)
	let db = sdr(result.stems.stem[0], L)
	ok(db > 60, `SDR ${db.toFixed(1)} dB`)
})

// ------------------------------------------------------- 8. Real model (skipped)

const MODELS_DIR = process.env.AUDIO_NEURAL_MODELS
const hasRealModels = MODELS_DIR && existsSync(`${MODELS_DIR}/umxhq-vocals.onnx`)

;(hasRealModels ? test : test.skip)('separate — real umxhq weights (AUDIO_NEURAL_MODELS)', async () => {
	let fs = 44100, N = Math.round(fs * 5)
	let x = sine([220, 440], 0.3, fs, N)
	let result = await separate([x, x], {
		sampleRate: fs,
		model: { vocals: `${MODELS_DIR}/umxhq-vocals.onnx` },
		modelType: 'openunmix',
	})
	ok(result.stems.vocals[0].length === N, 'vocals stem produced')
})

// ------------------------------------------------------------------- Speed

test('speed — mock pipeline (STFT + Wiener + iSTFT), 60 s stereo < 4 s', async () => {
	let fs = 44100, N = Math.round(fs * 60)
	let x = sine([90, 300], 0.3, fs, N)
	let model = { bass: 'b', vocal: 'v' }
	let sessionFactory = async spec => spec === 'b' ? bandMaskSession(0, 250, 4096, fs) : bandMaskSession(250, fs / 2, 4096, fs)

	let t0 = performance.now()
	await separate([x, x], { sampleRate: fs, modelType: 'mask', model, session: sessionFactory, wiener: 1, chunk: 30, overlap: 2 })
	let elapsed = (performance.now() - t0) / 1000
	console.log(`  (60 s stereo, 2 targets, wiener:1: ${elapsed.toFixed(2)} s)`)
	ok(elapsed < 4, `elapsed ${elapsed.toFixed(2)} s`)
})

// --------------------------------------------------------------- input errors

test('separate — rejects on missing sampleRate / model', async () => {
	await rejects(() => separate([new Float32Array(4)], {}), /sampleRate/, 'missing sampleRate')
	await rejects(() => separate([new Float32Array(4)], { sampleRate: 44100 }), /model/, 'missing model')
})
